import 'dart:ffi';

import 'package:book_my_seat/book_my_seat.dart';
import 'package:bookmyshowclone/models/constants.dart';
import 'package:bookmyshowclone/screens/showTicket.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:razorpay_web/razorpay_web.dart';

class SeatsListings extends StatefulWidget {
  const SeatsListings({super.key});

  @override
  State<SeatsListings> createState() => _SeatsListingsState();
}

class _SeatsListingsState extends State<SeatsListings> {
  int neededSeats = 1;
  int selectedSeatCount = 0;
  String selectionImages = 'assets/images/bicycle.png';
  int calculatedPrice = 0;
  bool isLoading = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      showBottomSheet(
        context: context,
        builder: (context) {
          return StatefulBuilder(
            builder: (BuildContext context, StateSetter setBottomSheetState) {
              return Container(
                width: MediaQuery.of(context).size.width,
                height: 250,
                decoration: BoxDecoration(
                    color: Colors.white24,
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(20),
                      topRight: Radius.circular(20),
                    )),
                padding: EdgeInsets.all(16.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  // Ensures the bottom sheet takes only required height
                  children: [
                    Image.asset(
                      selectionImages,
                      height: 100,
                      width: 100,
                      fit: BoxFit.cover,
                    ),
                    SizedBox(height: 10),
                    Container(
                      height: 40,
                      width: MediaQuery.of(context).size.width,
                      alignment: Alignment.center,
                      child: SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: List.generate(
                            seatOptions.length,
                            (index) {
                              final seatSelectionOptions = seatOptions[index];
                              return Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: GestureDetector(
                                  onTap: () {
                                    setBottomSheetState(() {
                                      final chosenSeatDetails =
                                          seatOptions[index];
                                      calculatedPrice = 0;
                                      selectionImages =
                                          chosenSeatDetails['image'];
                                      neededSeats = chosenSeatDetails['number'];
                                      print(chosenSeatDetails);
                                    });
                                  },
                                  child: Container(
                                    height: 40,
                                    width: 40,
                                    alignment: Alignment.center,
                                    decoration: BoxDecoration(
                                      color: neededSeats == index + 1
                                          ? kPrimary
                                          : Colors.white,
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                    child: Text(
                                      seatSelectionOptions['number'].toString(),
                                      style: TextStyle(
                                          color: neededSeats == index + 1
                                              ? Colors.white
                                              : Colors.black,
                                          fontFamily: subtitleFonts),
                                    ),
                                  ),
                                ),
                              );
                            },
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    GestureDetector(
                      onTap: () {
                        setBottomSheetState(() {
                          calculatedPrice = 0;
                          calculatedPrice = calculatedPrice + neededSeats * 200;
                          print(calculatedPrice);
                          Navigator.pop(context);
                        });
                      },
                      child: Container(
                        height: 38,
                        width: MediaQuery.of(context).size.width - 40,
                        decoration: BoxDecoration(
                            color: kPrimary,
                            borderRadius: BorderRadius.circular(10)),
                        alignment: Alignment.center,
                        child: Text(
                          'Select seats',
                          style: TextStyle(
                              color: Colors.white, fontFamily: primaryFont),
                        ),
                      ),
                    )
                  ],
                ),
              );
            },
          );
        },
      );
    });
  }

  Widget build(BuildContext context) {
    return Column(
      children: [
        Image.asset(
          'assets/images/screen.png',
          width: MediaQuery.of(context).size.width - 40,
        ),
        Container(
          child: Padding(
            padding: const EdgeInsets.all(20.0),
            child: SeatLayoutWidget(
              stateModel: SeatLayoutStateModel(
                rows: 22,
                cols: 20,
                currentSeatsState: [
                  [
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.disabled,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.disabled,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                  ],
                  [
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                  ],
                  [
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.disabled,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.disabled,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                  ],
                  [
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                    SeatState.empty,
                  ],
                  [
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.unselected,
                    SeatState.sold,
                    SeatState.sold,
                  ],
                ],
                seatSvgSize: 17,
                pathSelectedSeat: 'assets/images/seat_selected.svg',
                pathDisabledSeat: 'assets/images/seat_disabled.svg',
                pathSoldSeat: 'assets/images/seat_sold.svg',
                pathUnSelectedSeat: 'assets/images/seat_unselected.svg',
              ),
              onSeatStateChanged: (int rowI, int colI, SeatState currentState) {
                print(currentState);
                if (currentState == SeatState.selected) {
                  selectedSeatCount = selectedSeatCount + 1;
                } else if (currentState == SeatState.unselected) {
                  selectedSeatCount = selectedSeatCount - 1;
                  setState(() {});
                }
                if (selectedSeatCount == neededSeats) {
                  setState(() {});
                }
                print(selectedSeatCount);
              },
            ),
          ),
        ),
        SizedBox(
          height: 30,
        ),
        Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SvgPicture.asset(
              'assets/images/seat_selected.svg',
              height: 30,
              width: 30,
            ),
            Text(
              'Selected seat',
              style: TextStyle(color: Colors.black, fontSize: 12),
            ),
            SizedBox(
              width: 8,
            ),
            SvgPicture.asset(
              'assets/images/seat_unselected.svg',
              height: 30,
              width: 30,
            ),
            Text(
              'Available seat',
              style: TextStyle(color: Colors.black, fontSize: 12),
            ),
            SizedBox(
              width: 8,
            ),
            SvgPicture.asset(
              'assets/images/seat_sold.svg',
              height: 30,
              width: 30,
            ),
            Text(
              'Sold seat',
              style: TextStyle(color: Colors.black, fontSize: 12),
            ),
            SizedBox(
              width: 5,
            ),
          ],
        ),
        Spacer(),
        selectedSeatCount == neededSeats
            ? GestureDetector(
                onTap: () {
                  setState(() {
                    isLoading = true;
                  });

                  Razorpay razorpay = Razorpay();

                  razorpay.on(
                      Razorpay.EVENT_PAYMENT_ERROR, handlePaymentErrorResponse);
                  razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS,
                      handlePaymentSuccessResponse);
                  razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET,
                      handleExternalWalletSelected);

                  var options = {
                    'key': 'rzp_test_Bonc0fLChoIiQP',
                    'amount': calculatedPrice*100,
                    'name': 'GS App Studio',
                    'description': 'Movie Ticket',
                    'retry': {'enabled': false, 'max_count': 1},
                    'send_sms_hash': true,
                    'prefill': {
                      'contact': '8888888888',
                      'email': 'test@razorpay.com'
                    },
                    'external': {
                      'wallets': ['paytm']
                    }
                  };

                  try {
                    razorpay.open(options);
                  } catch (e) {
                    print('Error opening Razorpay: $e');
                  } finally {
                    setState(() {
                      isLoading = false;
                    });
                  }
                  print(isLoading);
                },
                child: Container(
                  height: 48,
                  alignment: Alignment.center,
                  width: MediaQuery.of(context).size.width - 40,
                  decoration: BoxDecoration(
                      color: kPrimary, borderRadius: BorderRadius.circular(10)),
                  child: isLoading
                      ? CircularProgressIndicator(
                          color: Colors.white,
                        )
                      : Text(
                          'Pay ₹' + calculatedPrice.toString(),
                          style: TextStyle(
                              color: Colors.white,
                              fontFamily: primaryFont,
                              fontSize: textSubTitle),
                        ),
                ),
              )
            : Container(),
        SizedBox(
          height: 30,
        )
      ],
    );
  }

  void handlePaymentErrorResponse(PaymentFailureResponse response) {
    print(response.code);
  }

  void handlePaymentSuccessResponse(PaymentSuccessResponse response) {
    Navigator.push(
        context, MaterialPageRoute(builder: (builder) => ShowTicket()));
    print(response.paymentId);
  }

  void handleExternalWalletSelected(PaymentSuccessResponse response) {
    print(response.paymentId);
  }
}
